# Generated by Django 4.2.4 on 2023-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paymentStatus',
            field=models.CharField(default='Not paid', max_length=20),
        ),
    ]
