# Generated by Django 4.2.1 on 2023-08-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_course_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
